#!/usr/bin/env bash

set -e
if [[ -z "$ANSIBLE_VERSION" ]]; then
  export ANSIBLE_VERSION='devel'
fi

dir=$HOME/.ansible/$ANSIBLE_VERSION

install="pip install ansible[azure]==$ANSIBLE_VERSION"
if [ $ANSIBLE_VERSION == 'devel' ]; then
  install="pip install git+https://github.com/ansible/ansible.git@devel"
  rm -rf $dir > /dev/null 2>&1
fi

if [ ! -d $dir ]; then
  mkdir $dir
  python -m virtualenv $dir
  /bin/bash -c "source $dir/bin/activate && $install && pip install pywinrm>=0.2.2 && deactivate"
fi