#!/usr/bin/env bash

set -e
if [[ -z "$ANSIBLE_VERSION" ]]; then
  export ANSIBLE_VERSION='devel'
fi

dir=$HOME/.ansible/$ANSIBLE_VERSION

install="pip install ansible[azure]==$ANSIBLE_VERSION"
if [[ $ANSIBLE_VERSION == 'devel' || ! -z "$ANSIBLE_URI" ]]; then
  if [[ -z "$ANSIBLE_URI" ]]; then
     export ANSIBLE_URI="https://github.com/ansible/ansible.git@devel"
  fi
  github_raw='raw.githubusercontent.com'
  slash='/'
  branch=${ANSIBLE_URI/.git@/$slash}
  github_content=${branch/github.com/$github_raw}
  install="pip install git+$ANSIBLE_URI && wget -O require.txt $github_content/packaging/requirements/requirements-azure.txt && pip install -r require.txt"
  rm -rf $dir > /dev/null 2>&1
fi

if [ ! -d $dir ]; then
  mkdir $dir
  python -m virtualenv $dir
  /bin/bash -c "source $dir/bin/activate && $install && pip install pywinrm && deactivate"
fi
